### ISSUE TITLE
关于THUAI5 CAPI部分架构的一些思考

### ISSUE THREAD

**Issue by wyj-source** [eesast/THUAI5#102]
## THUAI5类之间的耦合关系

总结一下`API` `MultiThreadCommunication` `Logic`三个类两两之间的耦合关系：

### API MultiThreadCommunication

在API中，需要调用MultiThreadCommunication中的Send方法，实现对信息的发送。

### Logic API

1. Logic中含有pState和pBuffer指针。Logic负责更新pState和pBuffer所指向的内容，API需要使用Logic中的pState指针，用于提取信息给用户。
2. Logic中有储存队友消息的队列（储存类型为`std::string`），需要将其信息传给API，从而实现API的队友通信功能。
3. API需要知道Logic中的counter（计数器）。

### Logic MultiThreadCommunication

1. Logic需要将自己的成员函数（包含线程处理等功能）传给MultiThreadCommunication作为OnReceive、OnClose的委托（回调函数）。

### 总结

1. Logic依赖于API和MultiThreadCommunication的实体
2. API和MultiThread只依赖于Logic的接口
3. API也依赖于MultiThreadCommunication的接口
4. MultiThreadCommunication不依赖于API

从总体上看，消息的流动顺序是Server->MultiThreadCommunication(OnReceive)->MultiThreadCommunication(Concurrentqueue)->Logic(pState,pBuffer)->API(pState)->Server(using Send)

## 解决方案

基于DIP原则，不妨设计以下接口：

```cpp
class ICommunication  // API中需要用到Communication的部分
{
protected:
    virtual void Send(Protobuf::MessageToServer& m2s)=0;
};

class ILogic2Communication // Communication中需要用到Logic的部分
{
protected:
    virtual void OnReceive(pointer_m2c p2M) = 0;
    virtual void OnClose() = 0;
};

class ILogic2API // API中需要用到Logic的部分
{
protected:
    virtual bool Empty() = 0;
    virtual bool GetInfo(std::string& s) = 0;
    virtual bool WaitThread() = 0;
    virtual int GetCounter() = 0;
    virtual State* GetpState() = 0;
};

class IAPI
{
public:
    /* 内容略，和之前相同 */
};
```

接口的实现方法：

```cpp
class Communication: public ICommunication
{
public:
    Communication(ILogic2Communication& logic) : logic(logic) {}
    // 虚函数（接口）的实现
    ...
    
private:
    ILogic2Communication& logic;
};

class API: public IAPI
{
public:
    API(ILogic2API& logic, ICommunication& comm) : logic(logic) , comm(comm) {}

private:
    ICommunication& comm;
    ILogic2API& logic;
};

class Logic: public ILogic2API, ILogic2Communication
{
public:
    // 虚函数（接口）的实现
    ...
        
    int Main()
    {
        pComm = std::make_shared<Communication>(*this);
        pAPI = std::make_shared<API>(*this, *pComm); 
        
        // 核心运行逻辑
        ...
    }
private:
    std::shared_ptr<Communication> pComm;
    std::shared_ptr<API> pAPI;
};
```

不知道这种架构如何？

**Comment by Timothy-LiuXuefeng** [comment]
@wyj-source 

+ 感觉 `ICommunication` 没太大必要，API 只需要依赖 `ILogic2API` 即可。
  + 理论上选手的主动行为，也属于游戏逻辑的一部分，所以发送消息的服务也由 `Logic` 来提供给 `API`。如果 `API` 和 `Logic` 中都保存有一份对 `Communication` 的引用显得比较冗余，而且增加了复杂程度。
  + 此外，`API` 的作用本就是给选手一个接口，作为对游戏逻辑的调用，因此直接与通信进行交互也不是很合适。  
    > 例如，如果 `API` 不依赖于通信，而只依赖于 `ILogic2API` 的话，我们甚至可以把它做成单机游戏而只修改 `ILogic2API` 的具体类 `Logic`，而 `API` 不需要做任何改动。  

+ 另外感觉 `ILogic2API` 和 `ILogic2Communication` 的命名有些怪怪的，感觉 `ILogic2API` 可以直接写成 `ILogic`，毕竟 API 需要的是一个游戏逻辑；而通信组件感觉可以命名为 `ISubscripter`，毕竟对于通信者来说，它需要的只是一个消息的订阅者，它对游戏逻辑并不关心。  

+ 关于 `pState`
  + 还有就是把 `pState` 暴漏给外部是一个比较危险的操作，很容易引起并发不安全的问题，包括现在的 `pState` 和 `pBuffer` 的实现就是有问题存在的。**关于这点，参见 issue** #100 
  + 还有就是，把 `Logic` 的 `pState` 暴露出来给 API 也是暴露了 `Logic` 的内部实现，若以后对 `Logic` 进行更改则也会很大程度影响 API，可见这样会使得两个类耦合性变强
  + 观察其他语言，如 C# 的线程安全容器，都是不允许访问其内部元素的，因为这会导致上面所述的问题。

**Comment by wyj-source** [comment]
收到！有时间我重构一下。

**Comment by Timothy-LiuXuefeng** [comment]
@wyj-source 
哦对了，还有就是对于 `pComm` 和 `pAI` 两个，`Logic` 对其有绝对的所有权，因此用 `unique_ptr` 应该更好些
