### ISSUE TITLE
关于CAPI的一些杂项问题

### ISSUE THREAD

**Issue by Ther-nullptr** [eesast/THUAI5#111]
## 概况

现在在win上和linux上理论可以跑了，但还存在一些大问题和小问题orzorz

## 程序运行

运行环境均为.NET 5.0 Debug x64。win和linux的运行情况相同。

以下为client端的运行截图。可以看到随时间的推移，玩家的坐标确实在发生变化。

![image-20220114204731870](https://user-images.githubusercontent.com/71265304/149521465-45a95880-598d-4902-90d4-0d6bc41fb28e.png)

以下为server端的运行截图。server端抛出了`Google.Protobuf.InvalidProtocolBufferException`。但似乎并未影响到Client和Server的运行。看输出应该是通信组件的问题，我再研究下。

![image-20220114204505469](https://user-images.githubusercontent.com/71265304/149521523-e4892da1-c250-4f3f-bd60-76a1361fc247.png)

## 静态库和动态库

所有需要用到的库我都放在了[https://cloud.tsinghua.edu.cn/d/b8be040bcfc543e096c0/](https://cloud.tsinghua.edu.cn/d/b8be040bcfc543e096c0/)
（注：此云盘中没有linux下的protobuf静态/动态库，原因下面会讲）

HPSocket版本：[https://github.com/ldcsaa/HP-Socket/releases/tag/v5.8.5](https://github.com/ldcsaa/HP-Socket/releases/tag/v5.8.5)

Protobuf版本：[https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.0)

### win

此处需要特别说明的是`HPSocket.lib`和`zlib.dll`。

在5.8.5的HPSocket中确实有一个`HPSocket.lib`（30000多K），但却无法使用，换成THUAI4（[https://cloud.tsinghua.edu.cn/d/151d53d424cb463686c9/](https://cloud.tsinghua.edu.cn/d/151d53d424cb463686c9/)）的`HPSocket.lib`（仅10多K）反而可以用了。。

`zlib.dll`是在[https://cn.dll-files.com/](https://cn.dll-files.com/)找的。不知道会不会存在版本问题。

### linux

以下为linux下可执行文件的链接情况：

![image-20220114205831931](https://user-images.githubusercontent.com/71265304/149521621-4e48b80d-8726-4e13-ab6e-ffb89e05cbf3.png)

需要指出的是，在5.8.5的HPSocket中只有`libhpsocket.so`和`libhpsocket_d.so`。在使用前需要改名为`libhpsocket.so.5`和`libhpsocket_d.so.5`，否则无法链接。我直接改了一下名字就可以了，不知道可不可以。。。

## cmake

cmake最麻烦的地方在于HPSocket库和Protobuf库的处理。

对于HPSocket库，我的处理方法是，直接将对应的.a和.so放在`CAPI/lib/a`或`CAPI/lib/so`下，然后直接链接。

```cmake
target_link_libraries(capi
    PUBLIC
        communication
        ${PROTOBUF_LIBRARY} 
        ${PROJECT_SOURCE_DIR}/lib/so/libhpsocket_d.so.5
        ${PROJECT_SOURCE_DIR}/lib/so/libhpsocket.so.5
        ${PROJECT_SOURCE_DIR}/lib/a/libhpsocket_d.a
        ${PROJECT_SOURCE_DIR}/lib/a/libhpsocket.a
)
```

对于Protobuf，由于cmake中有自动处理protobuf依赖的方法，而且我像处理HPSocket那样处理Protobuf时，cmake会报错，暂时还不知到如何处理。所以需要先手动编译protobuf，对应的库将会生成在`/usr/local/lib`中，之后调用cmake中内置的方法进行处理。

```cmake
find_package(Protobuf REQUIRED)

if (Protobuf_FOUND)
    include_directories(${PROTOBUF_INCLUDE_DIR})
else (Protobuf_FOUND)
    message(FATAL_ERROR "Protobuf Not Found")
endif(Protobuf_FOUND)
```

不知道有无比较好的统一解决方法。另外cmake是速成的，部分地方写得不简洁还请见谅。

## .gitignore

对相应目录下的`.gitignore`做了修改，主要是为了屏蔽静态库、动态库、可执行文件、CMakeLists.txt生成的附加文件等，不知道是否合乎规范。

## 一处设计改进

`API.h`中的`class IAPI`被拆分为了`class IAPI`（供用户使用）和`class IAPI_For_Logic`（供`class Logic`使用），前者是后者的基类。其目的只有一个：让`Logic`可以直接访问`StartTimer()`和`EndTimer()`方法，而不将这两个方法暴露给用户。不知道这样设计如何。。感觉有些小题大做。

**Comment by TCL606** [comment]
我觉得这个问题已经解决了，所以先关闭这个开放了几个月的issue了。
