### ISSUE TITLE
关于 logic 目录结构

### ISSUE THREAD

**Issue by Timothy-LiuXuefeng** [eesast/THUAI5#20]
现在的 logic 目录分配是这样的：
+ Preparation
  + Utility
  + Interface
  + GameObj
  + GameData
+ GameEngine
  + MoveEngine.cs
  + CollisionChecker.cs

这样分配目录没有使得引擎独立于具体的游戏（GameEngine 依赖于 Preparation）。 建议是引擎与游戏分离，便于以后的 THUAI 复用游戏引擎。  
建议目录结构如下（标注 csproj 表示该目录内含一个 C# 项目）：

+ GameEngine（或沿用名字 THUnity2D）
  + Utility (csproj)
  + Interface (csproj)
  + MoveEngine (csproj)
    + MoveEngine.cs
    + CollisionChecker.cs
+ GameData (csproj)
+ GameObj (csproj)

这样，GameEngine 作为游戏的引擎，不依赖于具体游戏的实现（GameObj）；而 MoveEngine 依赖于接口 Interface，再编写不同的游戏对象只需继承 GameEngine 中的 Interface 即可，GameEngine 不需要做任何改动，可以做到引擎与实现的解耦。

**Comment by Timothy-LiuXuefeng** [comment]
根据最近一次 pr，现在的 MoveEngine 仍然依赖于具体的游戏对象 GameObj，建议按照上面，改为依赖于引擎内置的接口

**Comment by birdx-007** [comment]
that is constructive!
