### ISSUE TITLE
关于地图逻辑的设计问题

### ISSUE THREAD

**Issue by Timothy-LiuXuefeng** [eesast/THUAI5#78]
可以看到，游戏逻辑多处使用了 `defaultMap`：    

![{IEBPTXL4}86(I%}NFC7($F](https://user-images.githubusercontent.com/65613511/142800949-a1d52002-f1f8-4131-b1d1-56e942c27d75.png)

同时，目前 MapInfo.cs 和 Map.cs 均存在如下的代码：

```csharp
public static PlaceType GetPlaceType(GameObj obj)
{
    /* Some code */
}
```

且后面的游戏逻辑依赖于此方法。根据此方法的代码可以看出，此方法用于获取默认地图的相关信息。  

从上面的设计可以看出，游戏逻辑严重依赖于默认地图。
这非常不利于地图的更换、自定义地图等功能的实现，即若想从外部读入地图几乎成了不可能的事情。而且，如果这样，`Map` 类传入 `mapResource` 的设计也变得毫无意义，因为这种设计导致 `mapResource` 的值只能为 `defaultMap`。  

因此，**强烈建议**解除游戏逻辑对 `MapInfo` 中默认地图的依赖关系，将设置游戏地图的逻辑移植到 `Server` 中处理。 
这样，`Server` 就可以任意指定游戏地图，从而实现自定义地图等功能，例如从 JSON 文件中读取地图信息，进而可以编写地图编辑器生成包含地图信息的 JSON 文件，等等，加大程序的灵活性。   

---

鉴于此，我个人的一个设计建议如下：  

在 `Map` 类中增加字段 `protoMapInfo`，用于存储传入地图的原始信息，并留有**只读**的访问接口：  

```csharp
class Map
{
    private readonly int[,] protoMapInfo;    // 不可以定义公有属性让外部访问到此字段，以防止数组元素被更改，因此定义下面的接口方法
    public int Row => protoMapInfo.GetLength(0);
    public int Col => protoMapInfo.GetLength(1);
    public int GetProtoMapInfo(int x, int y) => protoMapInfo[x, y];

    public Map(int[,] mapResoutce)
    {
        this.protoMapInfo = new int[mapResoutce.GetLength(0), mapResoutce.GetLength(1)];
        Array.Copy(mapResoutce, this.protoMapInfo, mapResoutce.Length);        // 需要深拷贝，以防止地图信息被外部意外更改
    }
}
```

然后，删除 `MapInfo.cs` 中的 `GetPlaceType` 方法，并且修改 Map.cs 中的该方法，将其完全移至 `Map` 中：  

```csharp
class Map
{
    public static PlaceType GetPlaceType(GameObj obj)
    {
        uint type = this.protoMapInfo[obj.Position.x / GameData.numOfPosGridPerCell, obj.Position.y / GameData.numOfPosGridPerCell];
        /* Some code */
    }
}
```

这样，后面的游戏逻辑代码就可以不依赖默认地图 `defaultMap`，而是通过对 `Map` 对象的访问而获取信息，例如，`PropManager` 中的遍历就可以改为：

```csharp
for (int i = 0; i < gameMap.Row; i++)
{
    for (int j = 0; j < gameMap.Col; j++)
    {
        if (   gameMap.GetProtoMapInfo(i, j) == (int)MapInfo.MapInfoObjType.Null
            || gameMap.GetProtoMapInfo(i, j) == (int)MapInfo.MapInfoObjType.Grass1
            || gameMap.GetProtoMapInfo(i, j) == (int)MapInfo.MapInfoObjType.Grass2
            || gameMap.GetProtoMapInfo(i, j) == (int)MapInfo.MapInfoObjType.Grass3 )
        {
            availableCellForGenerateProp.Add(GameData.GetCellCenterPos(i, j));
        }
    }
}
```

而 `defaultMap` 只需要在 `Server` 处传给 `Game` 即可，其余部分均不依赖于 `defaultMap`，这样 `Server` 就可以自由选择地图。甚至可以把 `defaultMap` 移至 `Server` 项目中。  

此外，草丛的可见性目前在客户端进行，因此在“隐身”技能中，对人物可见性的描述只需要考虑是否隐身即可，不再需要对草丛进行判断，因此对 `GetPlaceType` 的依赖可以完全去除，而且可以把 `PlaceType` 删除，而使用 `bool` 类型记录是否可见即可，而 `CanSee` 作为一个特征，最好定义为属性而非方法，而返回该 `bool` 变量。这样，`defaultMap` 的 `GetPlaceType` 便可以彻底去除。

**Comment by Timothy-LiuXuefeng** [comment]
@TCL606

**Comment by TCL606** [comment]
收到，引用defaultMap的确是我的失误，我到时候修改一下。

**Comment by TCL606** [comment]
目前server每帧都发整张地图给client，对defaultMap的依赖已完全解决
