### ISSUE TITLE
关于技能类的设计  

### ISSUE THREAD

**Issue by Timothy-LiuXuefeng** [eesast/THUAI5#79]
`CommonSkill` 和 `PassiveSkill` 看起来都是对行为的约束，改成 `Interface` 而非 `abstract class` 貌似更好一些

**Comment by Timothy-LiuXuefeng** [comment]
@TCL606

**Comment by TCL606** [comment]
收到。技能类有很多地方都是重复的，我之后会进行进一步的设计和修改。

**Comment by TCL606** [comment]
已经改成接口了
