### ISSUE TITLE
关于隐身与草丛的可见性问题

### ISSUE THREAD

**Issue by Timothy-LiuXuefeng** [eesast/THUAI5#84]
目前逻辑中的技能隐身和在草丛的可见性是在一起考虑的，但是这会有一些问题：  

+ 两种功能具有强耦合，扩展性差；  
+ 一些逻辑不太好实现，例如草丛里的人应该可以看到本草丛里的人，但是看不到其他草丛里的人，以及实验技能隐身的人，等等  

---

因此，与逻辑组初步商议，得到一个建设性方案如下：  
1. 服务器至少向客户端提供两种信息：人物是否正在处于使用技能的隐身状态、地图上草丛的位置，以及人物正在所处的位置  
2. 客户端（包括 CAPI、logic/Client、Unity）来判断可见性，基本逻辑为：
    + 若人物不在草丛里，则看不到技能隐身和在草丛里的玩家
    + 若人物在草丛里，则可以看得到与自己位于同一草丛的玩家，但是看不到技能隐身的玩家

即，服务器提供必要的信息，而可见性的判断全部移至客户端，这有利于广播机制的实现以及客户端的调试（例如调试模式下隐身者仍然可见但以另一种颜色显示，等等）。

**Comment by Timothy-LiuXuefeng** [comment]
@wyj-source @PLUTO-SCY @windowso @TCL606

**Comment by TCL606** [comment]
现在

**Comment by TCL606** [comment]
现在隐身和草丛已经解耦，隐身用专门的属性去控制。为了方便客户端使用，游戏逻辑中仍然实时维护角色的位置信息，并将该信息发送给客户端。
