### ISSUE TITLE
Message2Clients.proto设计问题

### ISSUE THREAD

**Issue by Sweetnow** [eesast/THUAI5#9]
https://github.com/eesast/THUAI5/blob/dev/dependency/proto/Message2Clients.proto 中message GameObjInfo中有不少数据项是随gameObjType改变的，而且还互相有重叠，这个不是一个好的设计，要求合作开发者需要通过注释来确定功能，而且未使用的数据项Protobuf默认置零可能导致意外的行为。

建议：

- 针对不同的gameObjType设计不同的message，例如CharactorInfo、BulletInfo等，然后在GameObjInfo中通过oneof语法组合起来。

另外，变量名的总体上是小驼峰风格，但有些地方采用了大驼峰，这个可以注意一下。

有兴趣的话也可以参考一下https://github.com/uber/prototool/blob/dev/style/README.md

**Comment by Timothy-LiuXuefeng** [comment]
确实，这是 THUAI4 的设计失误，THUAI5 更正一下吧
