### ISSUE TITLE
关于 CAPI/logic 的设计问题

### ISSUE THREAD

**Issue by Timothy-LiuXuefeng** [eesast/THUAI5#99]
提出两个建议。

## 一

最新一次的 pull request #98 中，CAPI/logic 的设计为，让 API 继承 LogicInterface，LogicInterface 通过回调函数调用 Logic 的相关接口。
从逻辑上看，由于 AI、API、Logic 在逻辑上存在相互之间的依赖关系，因此代码混杂、繁琐是很正常的事情，THUAI4 中出现了大量的回调机制就是逻辑上相互依赖导致的结果。目前使用建造者模式虽然有所缓解，但是仍然没有解决本质的问题。的回调机制就是逻辑上相互依赖导致的结果。目前使用建造者模式虽然有所缓解，但是仍然没有解决本质的问题。主要存在的问题有：

+ `LogicInterface` 的成员依赖于 `logic` 的生命周期，即外部的 `logic` 生命周期不可控，一旦 `logic` 的生命周期先于 `LogicInterface` 的生命期结束，那么再调用 `LogicInterface` 的成员将产生未定义行为，这增加了保证生命期顺序的包袱。

+ 仍然存在众多的回调函数作为参数，可读性仍然不高

+ ……

鉴于此，个人的建议是可以使用依赖倒转原则，在代码上消除相互的依赖来解决逻辑上的依赖关系，个人的想法如下：

将 `API` 要用到的 `Logic` 的属性抽象成接口 `LogicInterface`，`API` 仅与 `LogicInterface` 进行交互；`Logic` 实现接口 `LogicInterface`，这样便去除了依赖：

```cpp

///////////////////
//
// AI.cpp
//

interface IAI
{
    virtual void play(IAPI&) = 0;
};

class AI : IAI
{
    virtual void play(IAPI&) override;
};

///////////////////
//
// API.cpp
//

interface LogicInterface
{
    // 函数包装器全部改成虚函数
    virtual int GetCounter() const = 0；
    // 其他虚函数省略
    // 关于 State 的讨论在另外一个 issue 里讨论
};

interface IAPI { /* 内容略 */ };

class API : IAPI
{
   	API(LogicInterface& logic) : logic(logic) {}
	LogicInterface& logic;  // LogicInterface 作为其成员，供 API 调用
    // 利用 logic 实现 IAPI 的接口
};

// class DebugAPI : IAPI 同理

///////////////////
//
// Logic.cpp
//

using CreateAIFunc = ::std::function<::std::unique_ptr<IAI>(void)>;

class Logic : LogicInterface
{
    Logic();
    
    // 实现 LogicInterface 接口
    
    virtual int GetCounter() const override;
    /* 其他虚函数及 State 的实现 */
    
    int Main(CreateAIFunc createAI, ... /* args */ )
    {
        // 构造通信组件，挂载相应函数
        
        // 构造 API（如果有特殊需求甚至可以每次调用 play 均构造一次 API，不过目前来看还没有必要）
        API api(*this);
        
        // 构造 AI
        auto ai = createAI();
        
        // 启动 AI play 函数
        while (/* condition */)
        {
            /* 一些控制代码...... */
            
            // 调用 play 函数
            ai.play(api);
        }
        return 0;
    }
};

///////////////////
//
// main.cpp
//

int thuai5_main(const int argc, const char* const argv[], CreateAIFunc createAI)
{
    /* parse args */
    /* ... */
    return Logic{ createAI, /* args */ }.Main();
    // return ::std::make_unique<Logic>( createAI, /* args */ )->Main();  // If Logic is too big.
}

::std::unique_ptr<IAI> CreateAI()
{
    return ::std::make_unique<AI>();
}

int main(int argc, char* argv[])
{
    return thuai5_main(argc, argv, CreateAI);
}

```

这样代码也许会简洁很多。  
总结起来，依赖倒转就是，对于两个相互依赖的类，`A` 和 `B`，如果 `A` 只依赖 `B` 的接口，而 `B` 却依赖 `A` 的实体，换言之，`B` 具有对 `A` 的所有权。这时，就可以把 `B` 的被 `A` 依赖的方法提取出来形成接口 `C`，让 `A` 去依赖接口 `C` 即可去除 `A` 对 `B` 的直接依赖。  
不过正常情况下还是要尽量从设计上去除环形依赖，使用依赖倒转的公式可以作为最后的方法。  

---

## 二

此外还有一个小问题，`logic` 类内的一些辅助函数，诸如 `obj2C` 等，其本身与 `logic` 的关系并不大，也不会用到 `logic` 的任何属性，可以考虑将其单独拿出来放到一个工具类中，并声明成 `static` 的，这样既可以让代码清晰，也可以减少传递 `this` 指针的微量开销。

**Comment by wyj-source** [comment]
醍醐灌顶！我大致看了一下依赖倒转原则的一些使用方法。这一原则大致有三种实现形式：接口传递、构造器注入、方法注入。这个issue中用到的应该是构造器注入。这三种方法有孰优孰劣之分吗？（这决定了我要设计多少个类orz）

**Comment by Timothy-LiuXuefeng** [comment]
我说的依赖倒转原则是指的 DIP 原则 （Dependency Inversion Principle），是避免环形依赖的一个方法（把一个有向有环图变成一个有向无环图 x）；接口传递、构造器注入、方法注入好像是 Java 的一个框架来着（？），关于 DIP 原则可以参考（点击进入）[《Clean C++》](https://link.springer.com/content/pdf/10.1007%2F978-1-4842-2793-0.pdf)的第 153~158 页

**Comment by wyj-source** [comment]
我看的是这篇 https://blog.csdn.net/king123456man/article/details/81626127 这三种DIP的实现方法没什么区别吧 @Timothy-LiuXuefeng

**Comment by Timothy-LiuXuefeng** [comment]
应该，可以吧
